name: Update Submodule and Create Pull Request

on:
  workflow_dispatch:

env:
  SUBMODULE_NAME: "content" 
  GITHUB_TOKEN: ${{ secrets.PAT_CREATE_PR }}
  PULL_REQUEST_TITLE: "Update submodule to latest commit on main"
  PULL_REQUEST_BODY: "This pull request updates the submodule \"content\" to the latest commit on its main branch."

jobs:
  create_pull_request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Check for fresh commits to submodule
        id: check_submodule
        run: |
          cd ${{ env.SUBMODULE_NAME }}
          LOCAL_COMMIT=$(git rev-parse HEAD)
          REMOTE_COMMIT=$(git ls-remote origin -h refs/heads/main | cut -f1)
          if [ "$LOCAL_COMMIT" != "$REMOTE_COMMIT" ]; then
            echo "submodule_updated=true" >> $GITHUB_ENV
          fi

      - name: Update submodule
        if: env.submodule_updated == 'true'
        run: |
          git submodule update --remote ${{ env.SUBMODULE_NAME }}

      - name: Create Pull Request
        if: env.submodule_updated == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ env.GITHUB_TOKEN }}
          add-paths: ${{ env.SUBMODULE_NAME }}
          branch: ${{ env.SUBMODULE_NAME }}-submodule-update
          base: main
          title: "${{ PULL_REQUEST_TITLE }}"
          body: "${{ PULL_REQUEST_BODY }}"
